### ISSUE TITLE
Face when scheduling Org Mode event is invisible

### ISSUE THREAD

**Issue by mankoff** [humanoid-colors/emacs-humanoid-themes#1]
To replicate, make an `* Org Heading` and then `C-s` and then `+1` to schedule 1 day in the future. The minibuffer should show the selected date (today + 1 day), but does not.

Screenshot of humanoid-light:

![humanoid](https://user-images.githubusercontent.com/145117/72558727-21965800-3858-11ea-9c82-9473c1d6d16f.png)

Screenshot of a different theme loaded /after/ humanoid so things might look a bit weird.

![kaolin](https://user-images.githubusercontent.com/145117/72558741-2b1fc000-3858-11ea-978c-d109557254cc.png)

**Comment by tasmo** [comment]
Thank you for writing this issue.

I tested it in Spacemacs and Doom and got results with the expected display in the minibuffer:
![Screenshot from 2020-01-17 11-42-47](https://user-images.githubusercontent.com/102685/72606387-ced3a380-391e-11ea-883c-98a8c2ff4541.png)

So I'm not sure where to look.

**Comment by ogdenwebb** [comment]
Org-mode doesn't have a dedicated face for this part of minibuffer though, so org-mode uses secondary-selection face here.

**Comment by mankoff** [comment]
From [Emacs Manual](https://ftp.gnu.org/old-gnu/Manuals/emacs-21.2/html_node/emacs_193.html)

> You can control the appearance of the highlighting by customizing the secondary-selection face (see section AD.2.2.3 Customizing Faces).

But I'm not yet sure what to do with that information.

**Comment by tasmo** [comment]
The background for the `secondary-selection-face` is defined here:
https://github.com/humanoid-colors/emacs-humanoid-themes/blob/master/humanoid-themes.el#L231
As the foreground is not defined it inherits the foreground from the face before.

Can you try to unload all other themes before activating `humanoid-light`?

**Comment by mankoff** [comment]
Huh. Yes on a clean install there is no issue. I apologize, I thought I tested it without loading any other themes first.
