### ISSUE TITLE
Magit word diff highlight face w/ humanoid-light is too subtle

### ISSUE THREAD

**Issue by mankoff** [humanoid-colors/emacs-humanoid-themes#2]
Hello. I'm wary of this bug being due to my config because #1 was, but I'm pretty sure I'm only loading `humanoid-light` and nothing else.

The magit word diff highlight is too subtle (to my eyes) to be useful. See screenshot.

![magit](https://user-images.githubusercontent.com/145117/72981719-c1665f80-3ddd-11ea-8bae-6baa130be139.png)

**Comment by mankoff** [comment]
Much better. Thank you for the nice theme and responsive support.

I think the following might be a **magit issue** but am not certain. When the point is **outside** the diff, things now look great:

![outside](https://user-images.githubusercontent.com/145117/73141917-77090b00-4089-11ea-8a4e-14eaccf73e5b.png)


But when it is **inside** the diff, everything appears with a uniform hightlight:

![inside](https://user-images.githubusercontent.com/145117/73141919-7a9c9200-4089-11ea-8559-6ddfe8637ab6.png)

 Is this a humanoid issue, or should I take this up with magit?

**Comment by mankoff** [comment]
According to this closed magit bug https://github.com/magit/magit/issues/1848 it might be the theme that is introducing this issue.

**Comment by mankoff** [comment]
But, testing with `emacs -Q` and

```
(use-package magit
  :config (setq magit-diff-refine-hunk 'all))
```

shows this is not an issue with the default Emacs theme...

**Comment by tasmo** [comment]
Thank you for figuring out so far and opening this issue!

For my understanding, can you tell me which diff command you have taken?

**Comment by mankoff** [comment]
Just the normal magit diff and my entire magit config is shown above, with `magit-diff-refine-hunk` set to `'all`

Humanoid just updated this morning for me, and now I have the following default emacs them and humanoid comparison. With the latest update, word diff **does work** when the point is in the diff, but it is unreadable whether the point is in or out.

Default Theme:

![default](https://user-images.githubusercontent.com/145117/73165606-693c9f80-40f4-11ea-9891-c64ac719c14d.png)

Humanoid Theme:

![humanoid](https://user-images.githubusercontent.com/145117/73165607-69d53600-40f4-11ea-9d97-9fb3a9e1d374.png)

And here is my entire `DEBUG.org` file that I'm using to test this:

```Org
Run this debug Org file in a clean emacs session with

#+BEGIN_SRC bash :results verbatim
/usr/bin/emacs -Q ~/.emacs.d/DEBUG/DEBUG.org & 
#+END_SRC
#+RESULTS:

Initialize Emacs to reproduce this bug. Press `C-c C-c` in the Org Babel block below.

#+BEGIN_SRC emacs-lisp :results none :noweb yes
<<init_emacs>>
<<init_org>>
#+END_SRC

* Bug

** Magit highlight w/ Humanoid Theme

Eval the following code block and then view a diff with magit with a word change using the default emacs theme.

Notice that the word-level highlight is viewable both when the point is in the diff section or when it is not.

#+BEGIN_SRC emacs-lisp :results none
(use-package magit
  :config (setq magit-diff-refine-hunk 'all))
#+END_SRC

Load the humanoid theme and view the same diff with magit.

Notice that the word-level highlight disappears when the point is inside the diff region.

#+BEGIN_SRC emacs-lisp :results none
(use-package humanoid-themes
  :init (load-theme 'humanoid-light t))
#+END_SRC

* Init
** Emacs

#+NAME: init_emacs
#+BEGIN_SRC emacs-lisp :results none
(setq package-user-dir (expand-file-name "elpa" "~/.emacs.d/DEBUG"))

(require 'package)
(setq package-enable-at-startup nil)
(add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/") t)
(add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/") t)

(package-initialize)
;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))
(setq package-enable-at-startup nil)

(defvar use-package-verbose t)
(require 'use-package)
(setq use-package-always-ensure t)
;(setq use-package-always-defer t)
;; (require 'diminish)                ;; if you use :diminish
;; (require 'bind-key)   
#+END_SRC

** Org

#+NAME: init_org
#+BEGIN_SRC emacs-lisp :results none
(setq org-confirm-babel-evaluate nil) ;; don't ask to eval code
(org-babel-do-load-languages
 'org-babel-load-languages
 '((emacs-lisp . t)   
   (shell . t)))
#+END_SRC
```

**Comment by tasmo** [comment]
Thank you @mankoff, your screenshots helped a lot.
I found the issue in https://github.com/humanoid-colors/emacs-humanoid-themes/commit/35deb57cb8485d472ff4e875739da6f840586bb4#diff-68081a0f2797afd25d6b55899464b00fL711.
`magit-diff-added` had the same background as `diff-refine-added` which caused looking the same.
